In [6]:
from ctgan import CTGAN
from ctgan import load_demo

real_data = load_demo()

# Names of the columns that are discrete
discrete_columns = [
    'workclass',
    'education',
    'marital-status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'native-country',
    'income'
]

ctgan = CTGAN(epochs=10)
ctgan.fit(real_data, discrete_columns)

# Create synthetic data
synthetic_data = ctgan.sample(1000)

In [7]:
synthetic_data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,51,State-gov,491232,Assoc-acdm,9,Divorced,Exec-managerial,Not-in-family,White,Male,95,6,28,United-States,<=50K
1,30,Private,123985,Assoc-voc,9,Never-married,Machine-op-inspct,Own-child,Black,Male,76,-3,32,United-States,<=50K
2,47,Private,272624,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Female,121,0,50,United-States,<=50K
3,29,Private,125370,Some-college,9,Married-civ-spouse,Adm-clerical,Own-child,Black,Female,67,-3,16,United-States,<=50K
4,32,Federal-gov,171381,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,-29,-5,13,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,17,Local-gov,262783,Some-college,9,Married-civ-spouse,Farming-fishing,Unmarried,Asian-Pac-Islander,Male,9704,-1,34,United-States,<=50K
996,28,Private,465209,10th,11,Married-civ-spouse,Tech-support,Not-in-family,Black,Male,40,1,33,United-States,<=50K
997,50,Federal-gov,127742,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,-3,4,28,United-States,<=50K
998,30,Private,204867,HS-grad,9,Married-civ-spouse,Other-service,Unmarried,Black,Female,136,-2,44,United-States,>50K
999,48,Private,275377,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,Black,Female,123,2,48,Portugal,<=50K